spring.application.name=backend

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://ep-long-darkness-axpis0uo.c-4.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_l8rZXPbxiN0I
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Multipart File Uploads
spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=30MB

# Application Config
app.upload.dir=uploads/answer-sheets
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt.expiration-ms=86400000
app.ai-service.url=http://localhost:8000
app.ai-service.mock-fallback=true
app.moderation.variance-threshold=3.0
app.moderation.confidence-threshold=0.70